services:
  postfix:
    image: mailcow/postfix
    container_name: postfix
    environment:
      - maildomain=localhost
    ports:
      - "25:25"
    networks:
      - mail-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mail-network

  app:
    image: send-mail-service
    container_name: spring-boot-app
    depends_on:
      - postfix
      - mailhog
    ports:
      - "8080:8080"
    environment:
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    networks:
      - mail-network

networks:
  mail-network:
    driver: bridge